apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ivolve
data:
  MYSQL_DATABASE: aXZvbHZl
  MYSQL_PASSWORD: aXZvbHZlMTIz
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==
  MYSQL_USER: aXZvbHZlX3VzZXI=
