apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ivolve
type: Opaque
data:
  DB_USER: dGFoYQ==        # 'taha'
  DB_PASSWORD: dGFoYTEyMw==  # 'taha123'
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw== # 'root123'
